http:
  host: "0.0.0.0"
  port: "8081"

json-logger:
  data-to-mask: ""
  orgName : "Parsons"
  application:
    version : 1.0.0
    name : "parsons-syndeia-sapi"
  cloudhub:
    environment : ""
  sourceSystem: ""
  targetSystem: ""
  retryCounter: "0"
  errorSeverity: "Fatal"
  processName: ""
  category: "com.json-logger.PARSONS-SYNDEIA-SAPI"